# Generated by Django 4.2.3 on 2023-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_image_blogpost_image1_blogpost_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='quote',
            field=models.CharField(default='', max_length=150),
        ),
    ]
